// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: goscaffold/sdk/v1/entity_option.proto

package sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EntityOptions) Reset() {
	*x = EntityOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goscaffold_sdk_v1_entity_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityOptions) ProtoMessage() {}

func (x *EntityOptions) ProtoReflect() protoreflect.Message {
	mi := &file_goscaffold_sdk_v1_entity_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityOptions.ProtoReflect.Descriptor instead.
func (*EntityOptions) Descriptor() ([]byte, []int) {
	return file_goscaffold_sdk_v1_entity_option_proto_rawDescGZIP(), []int{0}
}

var file_goscaffold_sdk_v1_entity_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EntityOptions)(nil),
		Field:         51234,
		Name:          "goscaffold.sdk.v1.entity_options",
		Tag:           "bytes,51234,opt,name=entity_options",
		Filename:      "goscaffold/sdk/v1/entity_option.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional goscaffold.sdk.v1.EntityOptions entity_options = 51234;
	E_EntityOptions = &file_goscaffold_sdk_v1_entity_option_proto_extTypes[0]
)

var File_goscaffold_sdk_v1_entity_option_proto protoreflect.FileDescriptor

var file_goscaffold_sdk_v1_entity_option_proto_rawDesc = []byte{
	0x0a, 0x25, 0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2f, 0x73, 0x64, 0x6b,
	0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66,
	0x6f, 0x6c, 0x64, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a, 0x0d,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3a, 0x72, 0x0a,
	0x0e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xa2, 0x90, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x61,
	0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x03, 0x88, 0x01, 0x02, 0x52,
	0x0d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x2d, 0x73, 0x63, 0x61, 0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x64, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goscaffold_sdk_v1_entity_option_proto_rawDescOnce sync.Once
	file_goscaffold_sdk_v1_entity_option_proto_rawDescData = file_goscaffold_sdk_v1_entity_option_proto_rawDesc
)

func file_goscaffold_sdk_v1_entity_option_proto_rawDescGZIP() []byte {
	file_goscaffold_sdk_v1_entity_option_proto_rawDescOnce.Do(func() {
		file_goscaffold_sdk_v1_entity_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_goscaffold_sdk_v1_entity_option_proto_rawDescData)
	})
	return file_goscaffold_sdk_v1_entity_option_proto_rawDescData
}

var file_goscaffold_sdk_v1_entity_option_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_goscaffold_sdk_v1_entity_option_proto_goTypes = []interface{}{
	(*EntityOptions)(nil),               // 0: goscaffold.sdk.v1.EntityOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_goscaffold_sdk_v1_entity_option_proto_depIdxs = []int32{
	1, // 0: goscaffold.sdk.v1.entity_options:extendee -> google.protobuf.MessageOptions
	0, // 1: goscaffold.sdk.v1.entity_options:type_name -> goscaffold.sdk.v1.EntityOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goscaffold_sdk_v1_entity_option_proto_init() }
func file_goscaffold_sdk_v1_entity_option_proto_init() {
	if File_goscaffold_sdk_v1_entity_option_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goscaffold_sdk_v1_entity_option_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goscaffold_sdk_v1_entity_option_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_goscaffold_sdk_v1_entity_option_proto_goTypes,
		DependencyIndexes: file_goscaffold_sdk_v1_entity_option_proto_depIdxs,
		MessageInfos:      file_goscaffold_sdk_v1_entity_option_proto_msgTypes,
		ExtensionInfos:    file_goscaffold_sdk_v1_entity_option_proto_extTypes,
	}.Build()
	File_goscaffold_sdk_v1_entity_option_proto = out.File
	file_goscaffold_sdk_v1_entity_option_proto_rawDesc = nil
	file_goscaffold_sdk_v1_entity_option_proto_goTypes = nil
	file_goscaffold_sdk_v1_entity_option_proto_depIdxs = nil
}
