// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: goscaffold/api/v1/common.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Locale int32

const (
	Locale_LOCALE_UNSPECIFIED Locale = 0
)

// Enum value maps for Locale.
var (
	Locale_name = map[int32]string{
		0: "LOCALE_UNSPECIFIED",
	}
	Locale_value = map[string]int32{
		"LOCALE_UNSPECIFIED": 0,
	}
)

func (x Locale) Enum() *Locale {
	p := new(Locale)
	*p = x
	return p
}

func (x Locale) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Locale) Descriptor() protoreflect.EnumDescriptor {
	return file_goscaffold_api_v1_common_proto_enumTypes[0].Descriptor()
}

func (Locale) Type() protoreflect.EnumType {
	return &file_goscaffold_api_v1_common_proto_enumTypes[0]
}

func (x Locale) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Locale.Descriptor instead.
func (Locale) EnumDescriptor() ([]byte, []int) {
	return file_goscaffold_api_v1_common_proto_rawDescGZIP(), []int{0}
}

type PublicationState int32

const (
	PublicationState_PUBLICATION_STATE_UNSPECIFIED PublicationState = 0
)

// Enum value maps for PublicationState.
var (
	PublicationState_name = map[int32]string{
		0: "PUBLICATION_STATE_UNSPECIFIED",
	}
	PublicationState_value = map[string]int32{
		"PUBLICATION_STATE_UNSPECIFIED": 0,
	}
)

func (x PublicationState) Enum() *PublicationState {
	p := new(PublicationState)
	*p = x
	return p
}

func (x PublicationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicationState) Descriptor() protoreflect.EnumDescriptor {
	return file_goscaffold_api_v1_common_proto_enumTypes[1].Descriptor()
}

func (PublicationState) Type() protoreflect.EnumType {
	return &file_goscaffold_api_v1_common_proto_enumTypes[1]
}

func (x PublicationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicationState.Descriptor instead.
func (PublicationState) EnumDescriptor() ([]byte, []int) {
	return file_goscaffold_api_v1_common_proto_rawDescGZIP(), []int{1}
}

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_goscaffold_api_v1_common_proto_enumTypes[2].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_goscaffold_api_v1_common_proto_enumTypes[2]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_goscaffold_api_v1_common_proto_rawDescGZIP(), []int{2}
}

type Filtering struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Filtering) Reset() {
	*x = Filtering{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goscaffold_api_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filtering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filtering) ProtoMessage() {}

func (x *Filtering) ProtoReflect() protoreflect.Message {
	mi := &file_goscaffold_api_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filtering.ProtoReflect.Descriptor instead.
func (*Filtering) Descriptor() ([]byte, []int) {
	return file_goscaffold_api_v1_common_proto_rawDescGZIP(), []int{0}
}

type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	WithCount bool   `protobuf:"varint,3,opt,name=with_count,json=withCount,proto3" json:"with_count,omitempty"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goscaffold_api_v1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_goscaffold_api_v1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_goscaffold_api_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetWithCount() bool {
	if x != nil {
		return x.WithCount
	}
	return false
}

type Populate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Populate) Reset() {
	*x = Populate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goscaffold_api_v1_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Populate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Populate) ProtoMessage() {}

func (x *Populate) ProtoReflect() protoreflect.Message {
	mi := &file_goscaffold_api_v1_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Populate.ProtoReflect.Descriptor instead.
func (*Populate) Descriptor() ([]byte, []int) {
	return file_goscaffold_api_v1_common_proto_rawDescGZIP(), []int{2}
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Populate         *Populate        `protobuf:"bytes,1,opt,name=populate,proto3" json:"populate,omitempty"`
	Fields           []string         `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Filters          *Filtering       `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	Locale           []Locale         `protobuf:"varint,4,rep,packed,name=locale,proto3,enum=goscaffold.api.v1.Locale" json:"locale,omitempty"`
	PublicationState PublicationState `protobuf:"varint,5,opt,name=publication_state,json=publicationState,proto3,enum=goscaffold.api.v1.PublicationState" json:"publication_state,omitempty"`
	Sort             []*SortField     `protobuf:"bytes,6,rep,name=sort,proto3" json:"sort,omitempty"`
	Pagination       *Pagination      `protobuf:"bytes,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goscaffold_api_v1_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_goscaffold_api_v1_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_goscaffold_api_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Query) GetPopulate() *Populate {
	if x != nil {
		return x.Populate
	}
	return nil
}

func (x *Query) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Query) GetFilters() *Filtering {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *Query) GetLocale() []Locale {
	if x != nil {
		return x.Locale
	}
	return nil
}

func (x *Query) GetPublicationState() PublicationState {
	if x != nil {
		return x.PublicationState
	}
	return PublicationState_PUBLICATION_STATE_UNSPECIFIED
}

func (x *Query) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *Query) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SortField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Order SortOrder `protobuf:"varint,2,opt,name=order,proto3,enum=goscaffold.api.v1.SortOrder" json:"order,omitempty"`
}

func (x *SortField) Reset() {
	*x = SortField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goscaffold_api_v1_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_goscaffold_api_v1_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_goscaffold_api_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *SortField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SortField) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

var File_goscaffold_api_v1_common_proto protoreflect.FileDescriptor

var file_goscaffold_api_v1_common_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x22, 0x0b, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67,
	0x22, 0x5c, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x77, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x0a,
	0x0a, 0x08, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x86, 0x03, 0x0a, 0x05, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66,
	0x6f, 0x6c, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x36, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66,
	0x6f, 0x6c, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x31, 0x0a,
	0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65,
	0x12, 0x50, 0x0a, 0x11, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x67, 0x6f,
	0x73, 0x63, 0x61, 0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x10, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x12, 0x3d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x61,
	0x66, 0x66, 0x6f, 0x6c, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x73, 0x63, 0x61, 0x66, 0x66, 0x6f, 0x6c, 0x64,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2a, 0x20, 0x0a, 0x06, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x2a, 0x35, 0x0a, 0x10, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21,
	0x0a, 0x1d, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x2a, 0x27, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x16, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x63, 0x61, 0x66,
	0x66, 0x6f, 0x6c, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67,
	0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goscaffold_api_v1_common_proto_rawDescOnce sync.Once
	file_goscaffold_api_v1_common_proto_rawDescData = file_goscaffold_api_v1_common_proto_rawDesc
)

func file_goscaffold_api_v1_common_proto_rawDescGZIP() []byte {
	file_goscaffold_api_v1_common_proto_rawDescOnce.Do(func() {
		file_goscaffold_api_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_goscaffold_api_v1_common_proto_rawDescData)
	})
	return file_goscaffold_api_v1_common_proto_rawDescData
}

var file_goscaffold_api_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_goscaffold_api_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_goscaffold_api_v1_common_proto_goTypes = []interface{}{
	(Locale)(0),           // 0: goscaffold.api.v1.Locale
	(PublicationState)(0), // 1: goscaffold.api.v1.PublicationState
	(SortOrder)(0),        // 2: goscaffold.api.v1.SortOrder
	(*Filtering)(nil),     // 3: goscaffold.api.v1.Filtering
	(*Pagination)(nil),    // 4: goscaffold.api.v1.Pagination
	(*Populate)(nil),      // 5: goscaffold.api.v1.Populate
	(*Query)(nil),         // 6: goscaffold.api.v1.Query
	(*SortField)(nil),     // 7: goscaffold.api.v1.SortField
}
var file_goscaffold_api_v1_common_proto_depIdxs = []int32{
	5, // 0: goscaffold.api.v1.Query.populate:type_name -> goscaffold.api.v1.Populate
	3, // 1: goscaffold.api.v1.Query.filters:type_name -> goscaffold.api.v1.Filtering
	0, // 2: goscaffold.api.v1.Query.locale:type_name -> goscaffold.api.v1.Locale
	1, // 3: goscaffold.api.v1.Query.publication_state:type_name -> goscaffold.api.v1.PublicationState
	7, // 4: goscaffold.api.v1.Query.sort:type_name -> goscaffold.api.v1.SortField
	4, // 5: goscaffold.api.v1.Query.pagination:type_name -> goscaffold.api.v1.Pagination
	2, // 6: goscaffold.api.v1.SortField.order:type_name -> goscaffold.api.v1.SortOrder
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_goscaffold_api_v1_common_proto_init() }
func file_goscaffold_api_v1_common_proto_init() {
	if File_goscaffold_api_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goscaffold_api_v1_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filtering); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goscaffold_api_v1_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goscaffold_api_v1_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Populate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goscaffold_api_v1_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goscaffold_api_v1_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goscaffold_api_v1_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goscaffold_api_v1_common_proto_goTypes,
		DependencyIndexes: file_goscaffold_api_v1_common_proto_depIdxs,
		EnumInfos:         file_goscaffold_api_v1_common_proto_enumTypes,
		MessageInfos:      file_goscaffold_api_v1_common_proto_msgTypes,
	}.Build()
	File_goscaffold_api_v1_common_proto = out.File
	file_goscaffold_api_v1_common_proto_rawDesc = nil
	file_goscaffold_api_v1_common_proto_goTypes = nil
	file_goscaffold_api_v1_common_proto_depIdxs = nil
}
